### ISSUE TITLE
Run generated script from ChromeRobot script

### ISSUE THREAD

**Issue by buscseik** [joao-carloto/ChromeRobot#4]
I have seen this option on FireRobot to run generated script straight from your extension.
Is this feature also available in ChromeRobot?

**Comment by joao-carloto** [comment]
Unfortunately not. Until recently it was possible to start a process, on your host operative system, using the following plugin https://developer.chrome.com/extensions/npapi
But even then, this would send the chrome extension to a manual code review process and I doubt it would get approved to get into the chrome web store.
